name: __sv_projectName
options:
  createIntermediateGroups: true
  generateEmptyDirectories: true
  defaultConfig: Debug
  defaultSourceDirectoryType: syncedFolder

configs:
  Debug: debug
  Release: release

packages:
  Pow:
    url: https://github.com/EmergeTools/Pow
    from: 1.0.0

schemes:
  __sv_projectName:
    build:
      targets:
        __sv_projectName: all
    run:
      config: Debug
      debugEnabled: false
      gpuFrameCaptureMode: disabled
      gpuValidationMode: disabled
    profile:
      config: Debug
    analyze:
      config: Debug
    archive:
      config: Release

targets:
  __sv_projectName:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: __sv_projectName
        excludes:
          - "**/*.xcodeproj"
          - "**/*.xcworkspace"
          - ".build"
          - ".swiftpm"
          - "*.playground"
    dependencies:
      - package: Pow
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        MARKETING_VERSION: "1.0.0"
        ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: YES
        ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: YES
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "6.1.3"
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        DEVELOPMENT_TEAM: __sv_developmentTeam
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_IDENTITY: "Apple Development"
        PRODUCT_BUNDLE_IDENTIFIER: com.supervibes.__sv_projectName
        PRODUCT_NAME: __sv_projectName
        INFOPLIST_KEY_CFBundleDisplayName: __sv_projectName
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight UIInterfaceOrientationPortraitUpsideDown"
        INFOPLIST_KEY_UISupportedInterfaceOrientations~ipad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"

  __sv_projectNameTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: __sv_projectNameTests
        optional: true
    dependencies:
      - target: __sv_projectName
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "6.1.3"
        PRODUCT_BUNDLE_IDENTIFIER: com.supervibes.__sv_projectName.tests
        DEVELOPMENT_TEAM: __sv_developmentTeam
        CODE_SIGN_STYLE: Automatic
        TEST_HOST: $(BUILT_PRODUCTS_DIR)/__sv_projectName.app/$(BUNDLE_EXECUTABLE_FOLDER_PATH)/__sv_projectName

  __sv_projectNameUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - path: __sv_projectNameUITests
        optional: true
    dependencies:
      - target: __sv_projectName
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_VERSION: "6.1.3"
        PRODUCT_BUNDLE_IDENTIFIER: com.supervibes.__sv_projectName.uitests
        TEST_TARGET_NAME: __sv_projectName
        DEVELOPMENT_TEAM: __sv_developmentTeam
        CODE_SIGN_STYLE: Automatic
